@echo off
if exist index.js del index.js

type D:\myFile\gameserver2\build\db\CacheData.js >> index.js
type D:\myFile\gameserver2\build\db\HangVO.js >> index.js
type D:\myFile\gameserver2\build\db\MonsterVO.js >> index.js
type D:\myFile\gameserver2\build\db\PropVO.js >> index.js
type D:\myFile\gameserver2\build\db\SkillVO.js >> index.js
type D:\myFile\gameserver2\build\db\TecVO.js >> index.js
type D:\myFile\gameserver2\build\manager\CacheManager.js >> index.js
type D:\myFile\gameserver2\build\manager\TimeManager.js >> index.js

type D:\myFile\gameserver2\build\pk\data\PKStateListener.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\MBase.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\SBase.js >> index.js
type D:\myFile\gameserver2\build\pk\PKCode.js >> index.js
type D:\myFile\gameserver2\build\pk\PKConfig.js >> index.js
type D:\myFile\gameserver2\build\pk\PKMonsterAction.js >> index.js
type D:\myFile\gameserver2\build\pk\PKTool.js >> index.js
type D:\myFile\gameserver2\build\pk\data\PKBuffData.js >> index.js
type D:\myFile\gameserver2\build\pk\data\PKData.js >> index.js
type D:\myFile\gameserver2\build\pk\data\PKMonsterData.js >> index.js
type D:\myFile\gameserver2\build\pk\data\PKPlayerData.js >> index.js
type D:\myFile\gameserver2\build\pk\data\PKPosCardData.js >> index.js
type D:\myFile\gameserver2\build\pk\data\PKTeamData.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\M99.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M1.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M10.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M11.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M12.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M13.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M14.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M15.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M16.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M17.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M18.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M2.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M3.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M4.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M5.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M6.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M7.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M8.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\1\M9.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M31.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M32.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M33.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M34.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M35.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M36.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M37.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M38.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M39.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M40.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M41.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M42.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M43.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M44.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M45.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M46.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M47.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\2\M48.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M61.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M62.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M63.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M64.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M65.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M66.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M67.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M68.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M69.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M70.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M71.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M72.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M73.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M74.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M75.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M76.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M77.js >> index.js
type D:\myFile\gameserver2\build\pk\monsterData\3\M78.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\1\S101.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\1\S102.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\1\S103.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\1\S104.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\1\S105.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\1\S106.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\1\S107.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\1\S108.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\1\S109.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\1\S110.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\10\S191.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\10\S192.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\10\S193.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\10\S194.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\10\S195.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\10\S196.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\10\S197.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\10\S198.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\10\S199.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\2\S111.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\2\S112.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\2\S113.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\2\S114.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\2\S115.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\2\S116.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\2\S117.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\2\S118.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\2\S119.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\2\S120.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\3\S121.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\3\S122.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\3\S123.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\3\S124.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\3\S125.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\3\S126.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\3\S127.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\3\S128.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\3\S129.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\3\S130.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\4\S131.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\4\S132.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\4\S133.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\4\S134.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\4\S135.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\4\S136.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\4\S137.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\4\S138.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\4\S139.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\4\S140.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\5\S141.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\5\S142.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\5\S143.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\5\S144.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\5\S145.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\5\S146.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\5\S147.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\5\S148.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\5\S149.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\5\S150.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\6\S151.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\6\S152.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\6\S153.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\6\S154.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\6\S155.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\6\S156.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\6\S157.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\6\S158.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\6\S159.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\6\S160.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\7\S161.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\7\S162.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\7\S163.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\7\S164.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\7\S165.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\7\S166.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\7\S167.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\7\S168.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\7\S169.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\7\S170.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\8\S171.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\8\S172.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\8\S173.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\8\S174.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\8\S175.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\8\S176.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\8\S177.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\8\S178.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\8\S179.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\8\S180.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\9\S181.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\9\S182.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\9\S183.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\9\S184.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\9\S185.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\9\S186.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\9\S187.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\9\S188.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\9\S189.js >> index.js
type D:\myFile\gameserver2\build\pk\skillData\9\S190.js >> index.js


type D:\myFile\gameserver2\build\pkOther\AtkMVCtrl.js >> index.js
type D:\myFile\gameserver2\build\pkOther\PKCounter.js >> index.js
	
	
type D:\myFile\gameserver2\build\util\ArrayUtil.js >> index.js
type D:\myFile\gameserver2\build\util\ObjectUtil.js >> index.js
type D:\myFile\gameserver2\build\util\Base64.js >> index.js
type D:\myFile\gameserver2\build\util\md5.js >> index.js


type D:\myFile\gameserver2\build\main.js >> index.js
type D:\myFile\gameserver2\build\test.js >> index.js
echo done!
